### ISSUE TITLE
integration with NIRSTORM

### ISSUE THREAD

**Issue by Edouard2laire** [lpollonini/qt-nirs#3]
Hello, 

I recently attended your talk about nirs quality assessment for nirs; and found your tool very interesting. I was therefore wondering if you would be interested in having it integrated into our nirs toolbox: nirstorm : https://github.com/Nirstorm/nirstorm  (a plugin for brainstorm : https://neuroimage.usc.edu/brainstorm/)?

I can create a specific process that would call your toolbox (with proper citation of course)
If you are interested, I can send you a picture of how we could use your tool from nirstorm. 

Édouard

**Comment by lpollonini** [comment]
Hello Edouard,

Very interested, and thank you for reaching out. Anything you can share that would facilitate the integration/interfacing process would help tremendously!

Best,
Luca

**Comment by smonterohdz** [comment]
Closing the issue.
