### ISSUE TITLE
Issue with loading .snirf files

### ISSUE THREAD

**Issue by segoleneguerin** [lpollonini/qt-nirs#7]
**Bug Description**
I have multiple errors when I try to load .snirf files.

**To Reproduce**
1. Open the QT-NIRS GUI with `qtnirsLoadFileGUI`
2. Select the NIRS data folder with `Sel. Folder`
3. Click on the .snirf file name that is displayed in the GUI
4. See errors

**Errors**
Here the errors I have:
```
Unrecognized method, property, or field 'GetStim' for class 'StimClass'.

Error in SnirfClass/Get_s (line 1448)
                `[ts, v] = obj.stim(ii).GetStim();

Error in qtnirsLoadFileGUI/treeSelection (line 189)
                        `app.rawDotNirs.s = rawsnirf.Get_s;

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                `callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Tree PrivateSelectionChangedFcn.
```

**Desktop**
 - OS: macOS Ventura Version 13.1
 - MATLAB version: R2022a

**Comment by smonterohdz** [comment]
This error may be caused due to the existence of another snirf class folder in the current Matlab session . Please, verify if there is an additional snirf class folder in Matlab's path (Homer3 added its own snirf folder) if that is the case, move all the QTNIRS folders and subfolder to the top of the list in the Matlab's path.

**Comment by segoleneguerin** [comment]
Thank you for your answer Samuel! I cleaned my Matlab search paths with `restoredefaultpath` and added only the QT-NIRS path, but I have now these errors:

```
Method 'SnirfClass' is not defined for class 'SnirfClass' or is
removed from MATLAB's search path.

Error in qtnirsLoadFileGUI/treeSelection (line 187)
                        rawsnirf = SnirfClass([app.dotNirsPath,filesep,app.dotNirsFile]);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Tree PrivateSelectionChangedFcn.
```


Then, I also tried typing `setpaths` to set all the required Matlab search paths for snirf_homer3 (since in the previous errors, it seems like the snirf class was not known), and I have these errors:

```
Invalid or deleted object.

Error in StimClass/GetStim (line 279)
            if isempty(obj.data)

Error in SnirfClass/Get_s (line 1175)
                [ts, v] = obj.stim(ii).GetStim();

Error in qtnirsLoadFileGUI/treeSelection (line 189)
                        app.rawDotNirs.s = rawsnirf.Get_s;

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Tree PrivateSelectionChangedFcn.
```

**Comment by smonterohdz** [comment]
Thanks for the details. After digging more, I realized that there is a new incompatibility between QTNIRS and Homer3 regarding the SNIRF class definition. We will work on that, and it will take a bit more, though. 
In the meantime, **the quickest solution** to use QTNIRS on .snirf files is to have QTNIRS folders and subfolders in Matlab's path and remove Homer3 folders and subfolders from the path (they cannot coexist in Matlab's path at this moment). Once you are done with the quality analysis and want to use Homer3, you will need to do the opposite. Remove QTNIRS folders and subfolders and then, go to your Homer3 folder and run the _setpaths_ function to enable Homer3 folders.

**Comment by smonterohdz** [comment]
Ségolène:
I just uploaded the repository. As a temporary solution, now in order to work with snirf files in QTNIRS, Homer3 needs to be part of Matlab's path as well. Please, let us know if you still face problems.
Samuel
